name: Sync Renovate labels

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited, labeled, unlabeled]

permissions: {}

jobs:
  reconcile:
    permissions:
      issues: write
      pull-requests: write
    uses: PintjesB/github-runners/.github/workflows/_sync-renovate-merge-labels.yml@0358d0cf2cc49c6d9bfec5d921dd296d85c96b12 # main
