name: Sync Renovate labels

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited, labeled, unlabeled]

permissions: {}

jobs:
  reconcile:
    permissions:
      issues: write
      pull-requests: write
    uses: PintjesB/github-runners/.github/workflows/_sync-renovate-merge-labels.yml@ebb1b872d8854cb91caf9848f758539514dc47a4 # main
