name: Sync Renovate labels

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited, labeled, unlabeled]

permissions: {}

jobs:
  reconcile:
    permissions:
      issues: write
      pull-requests: write
    uses: PintjesB/github-runners/.github/workflows/_sync-renovate-merge-labels.yml@5f62af89bdcfd80d65e418731a8ef9c36f9dfd4d # main
